apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-techlover-cn
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: liuwenlongfox@163.com
    privateKeySecretRef:
      name: letsencrypt-prod-techlover-cn
    solvers:
    - selector: 
        dnsNames:
        - '*.techlover.cn'
      dns01:
        webhook:
          config:
            accessKeyId: LTAIIhN07wafdVmq
            accessKeySecretRef:
              key: accessKeySecret
              name: alidns-credentials-techlover-cn
            regionId: "cn-shenzhen"
            ttl: 600
          groupName: certmanager.webhook.alidns
          solverName: alidns
