---
# Create a selfsigned Issuer, in order to create a root CA certificate for
# signing webhook serving certificates
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "webhook-alidns.selfSignedIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook-alidns.name" . }}
    chart: {{ include "webhook-alidns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  selfSigned: {}

---

# Generate a CA Certificate used to sign certificates for the webhook
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "webhook-alidns.rootCACertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook-alidns.name" . }}
    chart: {{ include "webhook-alidns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ include "webhook-alidns.rootCACertificate" . }}
  duration: 43800h # 5y
  issuerRef:
    name: {{ include "webhook-alidns.selfSignedIssuer" . }}
  commonName: "ca.webhook-alidns.cert-manager"
  isCA: true

---

# Create an Issuer that uses the above generated CA certificate to issue certs
apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: {{ include "webhook-alidns.rootCAIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook-alidns.name" . }}
    chart: {{ include "webhook-alidns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ca:
    secretName: {{ include "webhook-alidns.rootCACertificate" . }}

---

# Finally, generate a serving certificate for the webhook to use
apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: {{ include "webhook-alidns.servingCertificate" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook-alidns.name" . }}
    chart: {{ include "webhook-alidns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  secretName: {{ include "webhook-alidns.servingCertificate" . }}
  duration: 8760h # 1y
  issuerRef:
    name: {{ include "webhook-alidns.rootCAIssuer" . }}
  dnsNames:
  - {{ include "webhook-alidns.fullname" . }}
  - {{ include "webhook-alidns.fullname" . }}.{{ .Release.Namespace }}
  - {{ include "webhook-alidns.fullname" . }}.{{ .Release.Namespace }}.svc

{{- if .Values.clusterIssuer.enabled }}
---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: {{ include "webhook-alidns.clusterIssuer" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    app: {{ include "webhook-alidns.name" . }}
    chart: {{ include "webhook-alidns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  acme:
{{- if .Values.clusterIssuer.staging }}
    server: https://acme-staging-v02.api.letsencrypt.org/directory
{{- else }}
    server: https://acme-v02.api.letsencrypt.org/directory
{{- end }}
    email: {{ .Values.clusterIssuer.email }}
    privateKeySecretRef:
      name: {{ include "webhook-alidns.fullname" . }}-letsencrypt
    solvers:
    - dns01:
        webhook:
          groupName: {{ .Values.groupName }}
          solverName: alidns
          config:
            accessKeyId: {{ required ".Values.secrets.accessKeyId is required" .Values.secrets.accessKeyId }}
            accessKeySecretRef:
              key: accessKeySecret
              name: {{ include "webhook-alidns.fullname" . }}-secret
            regionId: {{ required ".Values.regionId is required" .Values.regionId }}
            ttl: 600
      {{- if .Values.clusterIssuer.selector }}
      selector:
{{ toYaml .Values.clusterIssuer.selector | indent 8 }}
      {{- end }}
{{- end }}
