apiVersion: v1
kind: Secret
metadata:
  name: {{ include "webhook-alidns.fullname" . }}-secret
  labels:
    app: {{ include "webhook-alidns.name" . }}
    chart: {{ include "webhook-alidns.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  accessKeySecret: {{ required ".Values.secrets.accessKeySecret is required" .Values.secrets.accessKeySecret | b64enc | quote }}
